services:
    coreshop.inventory.availability_checker.default:
        class: CoreShop\Component\Inventory\Checker\AvailabilityChecker

    coreshop.templating.helper.inventory:
        class: CoreShop\Bundle\InventoryBundle\Templating\Helper\InventoryHelper
        tags:
            - { name: templating.helper, alias: coreshop_inventory }
        arguments:
          - '@coreshop.inventory.availability_checker'

    coreshop.twig.extension.inventory:
        class: CoreShop\Bundle\InventoryBundle\Twig\InventoryExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
          - '@coreshop.templating.helper.inventory'
